birth_year = input('Birth year: ')
print(type(birth_year))
age = 2020 - int(birth_year)
print(type(age))
print(age)
weight_lbs = input('How much do you weigh (lbs)? ')
weight_kg = int(weight_lbs) / int(2.2)
print(weight_kg)