course = 'Python for Beginners'
print(len(course))
print(course.upper())
print(course)
print(course.title())
print(course.lower())
print(course.find('P'))
print(course.find('e'))
print(course.replace('Beginners', 'Absolute Beginners'))
print('Python' in course)
print('python' in course)